name: Lint

on:
  push:
  pull_request:

jobs:
  grustonnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/koskev/grustonnet-ls:v0.1.0
        with:
          entrypoint: grustonnet-lint
          args: -j lib argocd lib
  tofu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/terraform-linters/tflint
        with:
          entrypoint: tflint
          args: --chdir tf
